[project]
name = "compgnn"
version = "0.0.1"
description = "compgnn"
readme = "README.md"
# license = {file = "LICENSE.txt"}
requires-python=">=3.9"

[tool.setuptools.packages.find]
exclude = ["results*"]