[project]
name = "invariant_gnode"
version = "0.0.1"
description = "Invariant_GNODE"
readme = "README.md"
# license = {file = "LICENSE.txt"}
requires-python=">=3.11"

[tool.setuptools.packages.find]
exclude = ["results*"]